baseURL = "https://www.bg117.xyz/home/"
languageCode = "en-us"
title = "Website Index"
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "bg117"
headline = "Index of www.bg117.xyz"
links = [
    { link = { href = "/home", text = "Home", target = "_self" } },
    { link = { href = "/projects", text = "Projects", target = "_self" } },
    { link = { href = "https://api.bg117.xyz/", text = "API", target = "_self" } },
]

[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
