baseURL = "https://www.bg117.xyz/home/"
languageCode = "en-us"
title = "Lynx"                          # 'cause links, get it?
theme = "lynx"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
name = "bg117"
headline = "My links"
links = [
    { link = { text = "Home", href = "/home" } },
    { link = { text = "Projects", href = "/projects" } },
    { github = "https://github.com/bg117" },
    { stack-overflow = { text = "Stack Overflow", href = "https://stackoverflow.com/users/14858708/bg117" } },
    { reddit = "https://reddit.com/u/Sorry-Chair" },
    { youtube = "https://www.youtube.com/channel/UCPnD_7cC4obyh9DltdFuYrQ" },
    { discord = { text = "bg117#6969" } },
    { email = { text = "me@bg117.xyz", href = "mailto:me@bg117.xyz" } },
]

[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
